http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    paths: '/api/*'
    target: http://localhost:5050
serviceEndpoints:
  httpbin:
    url: 'http://localhost:5050'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
